services:
  opend:
    build: .
    image: moomoo-opend:10.11
    container_name: moomoo-opend
    restart: unless-stopped
    stdin_open: true
    tty: true

    ports:
      - "11111:11111"

    volumes:
      - opend-state:/root/.com.moomoo.OpenD/F3CNN

volumes:
  opend-state:
