services:
  opend:
    build: .
    container_name: moomoo-opend
    restart: unless-stopped
    stdin_open: true
    tty: true

    ports:
      - "11111:11111"

    expose:
      - "22222"

    volumes:
      - opend-state:/root/.com.moomoo.OpenD/F3CNN

  login-ui:
    build: ./login-ui
    container_name: moomoo-opend-login
    restart: unless-stopped

    ports:
      - "6789:6789"

    volumes:
      - opend-state:/root/.com.moomoo.OpenD/F3CNN:ro

    depends_on:
      - opend


  cerebro:
    build: ./cerebro
    container_name: cerebro
    restart: unless-stopped

    ports:
      - "7000:7000"

    depends_on:
      - opend

volumes:
  opend-state:
